version: "3.8"

services:
  host:
    build:
      context: .
      dockerfile: host/Dockerfile
    ports:
      - "3001:3000" # Host API
    environment:
      - HOST_ID=1
      - SERVER_URL=http://frontend:3000
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
